from neo4j import GraphDatabase
import os
import datetime

URI = "bolt://localhost:7687"
AUTH = ("neo4j", "12345678")  # Provide your neo4j database password here

try:
    driver = GraphDatabase.driver(URI, auth=AUTH)
    print("Neo4j python driver initialized")
except Exception as e:
    print(f"Failed to initialize Neo4j python driver: {e}")
    driver = None

def init_neo4j():
    """Create constraints to avoid duplicate nodes"""
    if not driver:
        return
    
    constraint_queries = [
        "CREATE CONSTRAINT IF NOT EXISTS FOR (s:Student) REQUIRE s.username IS UNIQUE",
        "CREATE CONSTRAINT IF NOT EXISTS FOR (s:Session) REQUIRE s.id IS UNIQUE",
        "CREATE CONSTRAINT IF NOT EXISTS FOR (e:MalpracticeEvent) REQUIRE e.id IS UNIQUE",
    ]
    
    with driver.session() as session:
        for q in constraint_queries:
            try:
                session.run(q)
            except Exception as e:
                print(f"Constraint creation error: {e}")

def create_session_node(session_id, username, start_time):
    """Log when a proctoring session starts for a user"""
    if not driver:
        return
        
    query = """
    MERGE (user:Student {username: $username})
    MERGE (sess:Session {id: $session_id})
    SET sess.start_time = $start_time
    MERGE (user)-[:PARTICIPATED_IN]->(sess)
    """
    
    with driver.session() as session:
        session.run(query, username=username, session_id=session_id, start_time=start_time)

def log_malpractice_event_to_neo4j(session_id, username, event_type, description, evidence_path):
    """Log a specific malpractice event generated by YOLO/Mediapipe"""
    if not driver:
        return
        
    event_id = f"evt_{datetime.datetime.now().strftime('%Y%m%d%H%M%S%f')}"
    
    query = """
    MATCH (user:Student {username: $username})
    MATCH (sess:Session {id: $session_id})
    
    CREATE (event:MalpracticeEvent {
        id: $event_id,
        type: $event_type,
        description: $description,
        evidence: $evidence_path,
        time: datetime()
    })
    
    CREATE (event)-[:COMMITTED_BY]->(user)
    CREATE (event)-[:OCCURRED_DURING]->(sess)
    """
    
    with driver.session() as session:
        session.run(query, username=username, session_id=session_id, 
                    event_id=event_id, event_type=event_type, 
                    description=description, evidence_path=evidence_path)

def get_graph_data():
    """Fetch nodes and edges formatted for vis.js network graph"""
    if not driver:
        print("Driver not initialized, returning empty graph")
        return {"nodes": [], "edges": []}
        
    query = """
    MATCH (n)
    OPTIONAL MATCH (n)-[r]->(m)
    RETURN n, r, m
    LIMIT 500
    """
    
    nodes = []
    edges = []
    node_ids = set()
    edge_ids = set()
    
    try:
        with driver.session() as session:
            result = session.run(query)
            for record in result:
                n = record["n"]
                m = record["m"]
                r = record["r"]
                
                # Format node n
                if n and n.element_id not in node_ids:
                    node_ids.add(n.element_id)
                    labels = list(n.labels)
                    label = labels[0] if labels else "Unknown"
                    
                    title = dict(n)
                    display_name = title.get("username", title.get("type", title.get("id", "Node")))
                    
                    group = 1
                    if label == "Student": group = 1
                    elif label == "MalpracticeEvent": group = 2
                    elif label == "Session": group = 3
                    
                    nodes.append({
                        "id": n.element_id,
                        "label": f"{label}\\n{display_name}",
                        "title": str(title),
                        "group": group
                    })
                
                # Format node m
                if m and m.element_id not in node_ids:
                    node_ids.add(m.element_id)
                    labels = list(m.labels)
                    label = labels[0] if labels else "Unknown"
                    
                    title = dict(m)
                    display_name = title.get("username", title.get("type", title.get("id", "Node")))
                    
                    group = 1
                    if label == "Student": group = 1
                    elif label == "MalpracticeEvent": group = 2
                    elif label == "Session": group = 3
                    
                    nodes.append({
                        "id": m.element_id,
                        "label": f"{label}\\n{display_name}",
                        "title": str(title),
                        "group": group
                    })
                    
                # Format relationships
                if r and r.element_id not in edge_ids:
                    edge_ids.add(r.element_id)
                    edges.append({
                        "id": r.element_id,
                        "from": r.start_node.element_id,
                        "to": r.end_node.element_id,
                        "label": r.type
                    })
                    
        return {"nodes": nodes, "edges": edges}
        
    except Exception as e:
        print(f"Error fetching graph: {e}")
        return {"nodes": [], "edges": []}

